### ISSUE TITLE
I love you man！ This is absolutely what I need.

### ISSUE THREAD

**Issue by 903496130** [claudio-silva/claude-artifact-runner#11]
Really useful project.

**Comment by claudio-silva** [comment]
I love this kind of issue! 😀

Thank you very much for your feedback! I'm glad to hear that the project is useful to you.

If you have any additional comments about how you use it, what you like or dislike about it, or what could be improved, please share them here.

I think I'm going to leave this issue open for a while.. It's such a nice issue to have open... 😉

**Comment by claudio-silva** [comment]
Hi @903496130, have you checked out the recently added support for multiple artifacts and multi-page applications? Let me know what you think.
Meanwhile, I'll close this issue, as it's not really an issue. ;-)
