### ISSUE TITLE
Deprecated version of some packegs in npm are in use

### ISSUE THREAD

**Issue by fragrusti** [claudio-silva/claude-artifact-runner#5]
Hi all, I just installed claude-artifact-runner today and npm says:

`npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead`

running it on:

`➜  ~ npm --version
10.8.2
➜  ~ sw_vers
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A335`

Just my two cents.

Thank you for your project, it's awesome!

Regards,
f.

**Comment by claudio-silva** [comment]
Hi @fragrusti

Thank you for taking the time to report this issue.
It is fixed now. You should get this output:
```
> npm install
added 426 packages, and audited 427 packages in 5s

70 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I'm glad you find this project useful :-)

Regards,
Cláudio
